services:
  gateway-service:
    image: 267837905230.dkr.ecr.ap-northeast-2.amazonaws.com/board-system/gateway-service:latest
    ports:
      - "8000:8080"
    environment:
      SERVER_PORT: 8080
      JWT_SECRET: ${JWT_SECRET}
      USER_SERVICE_URL: http://host.docker.internal:8080
      BOARD_SERVICE_URL: http://host.docker.internal:8081