services:
  gateway-service:
    image: 267837905230.dkr.ecr.ap-northeast-2.amazonaws.com/board-system/gateway-service:latest
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      SERVER_PORT: 8080
      JWT_SECRET: ${JWT_SECRET}
      USER_SERVICE_URL: http://${USER_SERVICE_URL}
      BOARD_SERVICE_URL: http://${USER_SERVICE_URL}