server:
  port: 8080

spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
          - id: user-service
            uri: http://user-service:8080
            predicates:
            - Path=/api/users/**

          - id: board-service-jwt
            uri: http://board-service:8081
            predicates:
            - Path=/api/boards
            - Method=POST
            filters:
            - JwtAuthenticationFilter

          - id: board-service
            uri: http://board-service:8081
            predicates:
            - Path=/api/boards/**
