services:
  gateway-service:
    image: 267837905230.dkr.ecr.ap-northeast-2.amazonaws.com/board-system/gateway-service:${IMAGE_TAG}
    restart: unless-stopped
    ports:
      - "8080"
    env_file:
      - .env
    # environment:
    #   SERVER_PORT: ${SERVER_PORT}
    #   JWT_SECRET: ${JWT_SECRET}
    #   USER_SERVICE_URL: ${USER_SERVICE_URL}
    #   BOARD_SERVICE_URL: ${BOARD_SERVICE_URL}